version: "3.7"

services:
  webinterface:
    build:
      context: ./webinterface
    container_name: smarthome_webinterface
    restart: always
    ports:
      - 3000:3000

  homebridge:
    build:
      context: ./homebridge
    container_name: homebridge
    restart: always
    network_mode: host
    ports:
      - 51826:51826
      - 8765:8765

  mosquitto:
    build:
      context: ./mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - 9001:9001
      - 1883:1883

  command-gatway:
    build:
      context: : ./command_gateway
    container_name: command-gateway
    restart: always
    ports:
      - 3006:3006
