version: "3.7"

services:
  webinterface:
    build:
      context: ./webinterface
    env_file:
      - .env
    container_name: smarthome_webinterface
    restart: always
    ports:
      - $WEBINTERFACE_PORT

  bridge:
    build:
      context: ./bridge
    env_file:
      - .env
    container_name: smarthome_bridge
    restart: always
    ports:
      - $REST_API_PORT
      - $SOCKET_API_PORT
    # TODO: mount tty-ports (#11)

  mosquitto:
    build:
      context: ./mosquitto
    env_file:
      - .env
    container_name: mosquitto
    restart: always
    ports:
      - 9001:9001
      - $MQTT_PORT:$MQTT_PORT
