version: "3.7"

services:
  webinterface:
    build:
      context: ./webinterface
    env_file:
      - .env
    container_name: smarthome_webinterface
    restart: always
    ports:
      - $WEBINTERFACE_PORT:$WEBINTERFACE_PORT

  homebridge:
    build:
      context: ./homebridge
    container_name: homebridge
    restart: always
    network_mode: host
    ports:
      - 51826:51826
      - 8765:8765

  mosquitto:
    build:
      context: ./mosquitto
    env_file:
      - .env
    container_name: mosquitto
    restart: always
    ports:
      - 9001:9001
      - $MQTT_PORT:$MQTT_PORT

  smarthome_bridge:
    build:
      context: ./bridge
    env_file:
      - .env
    container_name: smarthome_bridge
    restart: always
    ports:
      - $REST_API_PORT:$REST_API_PORT